"""Create device tables

Revision ID: 450870701c24
Revises: 
Create Date: 2023-06-09 00:27:53.459830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450870701c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_device_model',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Device Models'
    )
    op.create_table('t_device_type',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Device Types'
    )
    op.create_table('t_device_vendor',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Device Vendors'
    )
    op.create_table('t_parameter_type',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('table_name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Parameter Types'
    )
    op.create_table('t_device_profile',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_device_type', sa.Integer(), nullable=False),
    sa.Column('id_device_model', sa.Integer(), nullable=False),
    sa.Column('id_device_vendor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_model'], ['t_device_model.id'], ),
    sa.ForeignKeyConstraint(['id_device_type'], ['t_device_type.id'], ),
    sa.ForeignKeyConstraint(['id_device_vendor'], ['t_device_vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Device Profiles'
    )
    op.create_table('t_parameter_content',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_parameter_type', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=1024), nullable=False),
    sa.Column('column_type', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_parameter_type'], ['t_parameter_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Parameter Content'
    )
    op.create_table('t_device',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_device_profile', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_profile'], ['t_device_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Devices'
    )
    op.create_table('t_device_profile_parameter',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_device_profile', sa.Integer(), nullable=False),
    sa.Column('id_parameter_type', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_profile'], ['t_device_profile.id'], ),
    sa.ForeignKeyConstraint(['id_parameter_type'], ['t_parameter_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'id_device_profile'),
    comment='Parameters in Device Profile'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_device_profile_parameter')
    op.drop_table('t_device')
    op.drop_table('t_parameter_content')
    op.drop_table('t_device_profile')
    op.drop_table('t_parameter_type')
    op.drop_table('t_device_vendor')
    op.drop_table('t_device_type')
    op.drop_table('t_device_model')
    # ### end Alembic commands ###
