"""Device*: added not null. Parameter*: added

Revision ID: 5e5afda50092
Revises: f585488fd8ad
Create Date: 2023-05-13 21:38:56.679793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5afda50092'
down_revision = 'f585488fd8ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_parameter_type',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('table_name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_parameter_content',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_parameter_type', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=1024), nullable=False),
    sa.Column('column_type', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_parameter_type'], ['t_parameter_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('t_device_profile_parameter', sa.Column('id_parameter_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 't_device_profile_parameter', 't_parameter_type', ['id_parameter_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_device_profile_parameter', type_='foreignkey')
    op.drop_column('t_device_profile_parameter', 'id_parameter_type')
    op.drop_table('t_parameter_content')
    op.drop_table('t_parameter_type')
    # ### end Alembic commands ###
