"""Create device tables

Revision ID: 79cdba98908a
Revises: 
Create Date: 2023-05-13 18:36:47.807734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cdba98908a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_device_model',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_device_type',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_device_vendor',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_device_profile',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('id_device_model', sa.Integer(), nullable=False),
    sa.Column('id_device_vendor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_model'], ['t_device_model.id'], ),
    sa.ForeignKeyConstraint(['id_device_vendor'], ['t_device_vendor.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['t_device_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_device',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_device_profile', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_profile'], ['t_device_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_device_profile_parameter',
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('id_device_profile', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_device_profile'], ['t_device_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_device_profile_parameter')
    op.drop_table('t_device')
    op.drop_table('t_device_profile')
    op.drop_table('t_device_vendor')
    op.drop_table('t_device_type')
    op.drop_table('t_device_model')
    # ### end Alembic commands ###
