"""Insert some data

Revision ID: d7ac18cb563c
Revises: 450870701c24
Create Date: 2023-06-09 00:51:24.524242

"""
from alembic import op
import sqlalchemy as sa
from db.models.parameter import *
from db.models.device import *

# revision identifiers, used by Alembic.
revision = 'd7ac18cb563c'
down_revision = '450870701c24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        DeviceType.__table__,
        [
            {'id': 1, 'name': 'Smartwatch'},
            {'id': 2, 'name': 'Smartband'},
        ]
    )
    op.bulk_insert(
        DeviceModel.__table__,
        [
            {'id': 1, 'name': 'Xiaomi Mi Smart Band 7'},
        ]
    )
    op.bulk_insert(
        DeviceVendor.__table__,
        [
            {'id': 1, 'name': 'Xiaomi'},
            {'id': 2, 'name': 'Garmin'},
        ]
    )
    op.bulk_insert(
        DeviceProfile.__table__,
        [
            {
                'id': 1,
                'name': 'Xiaomi Mi Smart Band 7 Profile',
                'id_device_type': 2,
                'id_device_model': 1,
                'id_device_vendor': 1,
            },
        ]
    )
    op.bulk_insert(
        ParameterType.__table__,
        [
            {'id': 1, 'name': 'Heart Rate', 'table_name': 'parameter_data_hr_general'},
            {'id': 2, 'name': 'Steps', 'table_name': 'parameter_data_steps'},
        ]
    )
    op.bulk_insert(
        DeviceProfileParameter.__table__,
        [
            {'id': 1, 'name': 'HR', 'id_device_profile': 1, 'id_parameter_type': 1},
            {'id': 2, 'name': 'Steps', 'id_device_profile': 1, 'id_parameter_type': 2},
        ]
    )
    op.bulk_insert(
        ParameterContent.__table__,
        [
            {
                'id': 1,
                'name': 'hr',
                'id_parameter_type': 1,  # HR
                'column_name': 'hr',
                'column_type': 'some-time-is-here',
            },
            {
                'id': 2,
                'name': 'steps',
                'id_parameter_type': 2,  # Steps
                'column_name': 'steps',
                'column_type': 'some-time-is-here',
            }
        ]
    )
    op.bulk_insert(
        Device.__table__,
        [
            {
                'id': 1,
                'name': 'Bracelet 1',
                'id_device_profile': 1,
            },
            {
                'id': 2,
                'name': 'Bracelet 2',
                'id_device_profile': 1,
            },
            {
                'id': 3,
                'name': 'Bracelet 3',
                'id_device_profile': 1,
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
