"""Device*: added constraints

Revision ID: f585488fd8ad
Revises: 79cdba98908a
Create Date: 2023-05-13 20:48:20.440478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f585488fd8ad'
down_revision = '79cdba98908a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 't_device_model', ['name'])
    op.create_unique_constraint(None, 't_device_profile', ['name'])
    op.create_unique_constraint(None, 't_device_profile_parameter', ['name', 'id_device_profile'])
    op.create_unique_constraint(None, 't_device_type', ['name'])
    op.create_unique_constraint(None, 't_device_vendor', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_device_vendor', type_='unique')
    op.drop_constraint(None, 't_device_type', type_='unique')
    op.drop_constraint(None, 't_device_profile_parameter', type_='unique')
    op.drop_constraint(None, 't_device_profile', type_='unique')
    op.drop_constraint(None, 't_device_model', type_='unique')
    # ### end Alembic commands ###
